# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=60)),
                ('postcode', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('ishub', models.BooleanField()),
                ('cardnumber', models.CharField(max_length=16)),
                ('securitynumber', models.CharField(max_length=3)),
            ],
        ),
    ]
