# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ishub',
        ),
        migrations.AddField(
            model_name='order',
            name='ai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='hubs',
            field=models.IntegerField(default=0),
        ),
    ]
