# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80, verbose_name='category')),
                ('slug', models.SlugField(max_length=80, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('text', models.TextField(blank=True, verbose_name='Message text')),
            ],
            options={
                'ordering': ('category',),
                'verbose_name': 'Text block',
                'verbose_name_plural': 'Text blocks',
            },
        ),
        migrations.AlterUniqueTogether(
            name='textblock',
            unique_together=set([('category', 'slug')]),
        ),
    ]
